### ISSUE TITLE
What does this program do and how to set it up?

### ISSUE THREAD

**Issue by caryknoop** [andrewbossie/vidpredict_model#2]
I installed it, put a video into a created video folder, 

I run python vidpredict.py predict and get:

```
Traceback (most recent call last):
  File "vidpredict.py", line 302, in <module>
    OneTimePredict(False)
  File "vidpredict.py", line 254, in OneTimePredict
    pred_image_tensor = importer.getPixelMatrix(pred_image_location)
  File "E:\vidpredict_model-master\src\classes\image.py", line 71, in getPixelMatrix
    im = PIL.Image.open(imageName)
  File "C:\Users\Cary\.conda\envs\vidpredict\lib\site-packages\PIL\Image.py", line 2809, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '../images/test_images/test.jpg'
```
I run python vidpredict.py import and get:

```
Traceback (most recent call last):
  File "vidpredict.py", line 294, in <module>
    VidPredict(True)
  File "vidpredict.py", line 64, in VidPredict
    for filename in os.listdir('../images/raw_data'):
FileNotFoundError: [WinError 3] The system cannot find the path specified: '../images/raw_data'
```
After creating images and images_raw_data it starts the training.

You might want to create ../video, ../images and ../images/raw_data folder or document the requirement.

A brief description of what this program actually does would be welcome and so is an example of a workflow.

**Comment by andrewbossie** [comment]
Thanks for the catch. image and video folders are in place now. You'll need to add your own videos you want to train on. As well as choose your own test image. (This is an untrained ML model)
